- name: Copy the basic configuration file for all the app examples
  ansible.builtin.copy:
    # TODO: find a better way to access the Python application example, maybe
    # with an ansible variable
    src: ../../../../examples/config.toml
    dest: ~/workspace/applications/
    owner: oracle
    group: oracle
    mode: '0644'
