---

# Configure all supported programming languages
- hosts: os_OracleLinux
  roles:
    - role: oraclelinux

# Copy the project to remotes if needed
- hosts: remotes
  roles:
    - role: app

# Configure all the programming languages
- hosts: localhost,remotes
  roles:
    - role: python
      tags: py
    - role: java
      tags: [ java, never ]
    - role: golang
      tags: [ go, never ]
