---

# Configure all supported programming languages
- hosts: os_OracleLinux
  roles:
    - role: oraclelinux

- hosts: remotes
  roles:
    - role: app
    - role: python
      tags: py
    - role: java
      tags: [ java, never ]
    - role: golang
      tags: [ go, never ]
