---

- import_playbook: system.yml

- name: Parse all the remotes to gather information from them
  hosts: remotes
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

# Orchestrate all roles and all tasks
- import_playbook: database.yml
- import_playbook: applications.yml
