---

- name: Parse all the remotes to gather information from them
  hosts: localhost,remotes
  tasks:
    - name: Classify hosts depending on their OS distribution
      group_by:
        key: os_{{ ansible_facts['distribution'] }}

# Orchestrate all roles and all tasks
- import_playbook: apps.yml
