- name: Install Python39
  become: true
  become_user: root
  become_method: su
  dnf:
    # Py39 is the last available version at the time of writing this role
    name: '@python39'   # Using the @ enable appstream module installation
    state: present

- name: Install poetry
  shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -

- name: Add Poetry to the PATH env var
  lineinfile:
    path: ~/.bash_profile
    line: "export PATH=$HOME/.poetry/bin:$PATH"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    # TODO: Put this absolute path within a variable
    path: ~/workspace/applications/py/Oracle-HA
    state: directory
    owner: oracle
    mode: '0755'

- name: Copy the whole Python application example
  ansible.builtin.copy:
    # TODO: find a better way to access the Python application example, maybe
    # with an ansible variable
    src: ../../../../examples/python/
    dest: ~/workspace/applications/py/Oracle-HA/
    owner: oracle
    group: oracle
    mode: '0644'

- name: Enable poetry and install dependencies
  shell:
    chdir: ~/workspace/applications/py/Oracle-HA/
    cmd: . ~/.bash_profile && poetry install
