- name: Remove previously pyenv installation
  ansible.builtin.file:
    path: ~/.pyenv
    state: absent

- name: Install pyenv
  ansible.builtin.shell:
    cmd: curl https://pyenv.run | bash

- name: Update .bashrc with pyenv binary
  ansible.builtin.blockinfile:
    path: ~/.bashrc
    marker: ""
    marker_begin: ""
    marker_end: ""
    block: |
      export PATH="~/.pyenv/bin:$PATH"
      eval "$(pyenv init -)"
      eval "$(pyenv virtualenv-init -)"

- name: Install Python3.10.5
  ansible.builtin.shell:
    cmd:  ~/.pyenv/libexec/pyenv install 3.10.5 && ~/.pyenv/libexec/pyenv local 3.10.5

- name: Install Poetry
  ansible.builtin.shell:
    cmd: curl -sSL https://install.python-poetry.org | python3 -

- name: Enable poetry and install dependencies
  ansible.builtin.shell:
    chdir: "{{ rmtdir }}/oracle-tac-apps/apps/python/"
    cmd: . ~/.bash_profile && poetry install

- name: Delete Poetry installation script
  ansible.builtin.file:
    path: /tmp/get-poetry.py
    state: absent
    remote_src: true
