- name: Connection test
  ping:
  tags: ping

- name: System update
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Vim
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name:
      - vim
    state: present
