- name: Copy the basic configuration file for all the app examples
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: ~/workspace/applications/
    owner: oracle
    group: oracle
    mode: '0644'
  with_items:
     - ../../../../apps/config.toml
     - ../../../../apps/raw.txt
