[database]
# User credentials
username = "sbuemi"
password = "sbuemi"

# Database schema
tableraw = "raw_tel"
tablejson = "json_tel"

[dsn]
# Connection strings
localhost = "localhost:1521:PDB"
default = "vmdb01/PDB"
ac = """(DESCRIPTION = \
        (CONNECT_TIMEOUT=120)(RETRY_COUNT=30) \
        (RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb01)(PORT=1521))) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb02)(PORT=1521))) \
        (CONNECT_DATA=(SERVICE_NAME = myacappsvc))) \
"""
tac = """(DESCRIPTION = \
         (CONNECT_TIMEOUT=120)(RETRY_COUNT=30) \
         (RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3) \
         (ADDRESS_LIST = \
         (LOAD_BALANCE=on) \
         (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb01)(PORT=1521))) \
         (ADDRESS_LIST = \
         (LOAD_BALANCE=on) \
         (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb02)(PORT=1521))) \
         (CONNECT_DATA=(SERVICE_NAME = mygoodappsvc))) \
"""

[ingest]
dumpfile = "../raw.txt"

[cleanup]
# This section is empty because filled at run-time
