[database]
# User credentials
username = "sbuemi"
password = "sbuemi"

# Connection strings
dsn1 = "localhost:1521/PDB"
dsn2 = "localhost:1521/mygoodappsvc"
dsn3 = """(DESCRIPTION = \
        (CONNECT_TIMEOUT=120)(RETRY_COUNT=30) \
        (RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb01)(PORT=1521))) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb02)(PORT=1521))) \
        (CONNECT_DATA=(SERVICE_NAME = PDB))) \
"""
dsn4 = """(DESCRIPTION = \
        (CONNECT_TIMEOUT=120)(RETRY_COUNT=30) \
        (RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb01)(PORT=1521))) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb02)(PORT=1521))) \
        (CONNECT_DATA=(SERVICE_NAME = mygoodappsvc))) \
"""
dsn5 = """(DESCRIPTION = \
        (CONNECT_TIMEOUT=120)(RETRY_COUNT=30) \
        (RETRY_DELAY=3)(TRANSPORT_CONNECT_TIMEOUT=3) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb01)(PORT=1521))) \
        (ADDRESS_LIST = \
        (LOAD_BALANCE=on) \
        (ADDRESS=(PROTOCOL=TCP)(HOST=vmdb02)(PORT=1521))) \
        (CONNECT_DATA=(SERVICE_NAME = myacappsvc))) \
"""
dsn6 = "HR"

# Database schema
tableraw = "raw_telemetry"
tablejson = "json_telemetry"

[injest]
dumpfile = "../raw.txt"

[cleanup]
