- name: System update
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install the Development Tools, Vim and Git
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - openssl-devel
      - vim
      - git
    state: present

