- name: Install the Development Tools and others
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name:
      - "@Development tools"
      - openssl-devel
      - vim
    state: present

- name: Configure the Oracle Instant Client reporitory
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name:
      - oracle-instantclient-release-el8
    state: latest

- name: System update
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name: "*"
    state: latest

- name: Install Oracle Instant Client package
  become: true
  become_user: root
  become_method: su
  ansible.builtin.dnf:
    name:
      - oracle-instantclient-basic
    state: latest
